blank_issues_enabled: true
contact_links:
  - name: Official Slimefun Discord Server
    url: https://slimefun.dev/discord
    about: You can ask stuff about LiteXpansion in the channel "#litexpansion"
